# This file was automatically generated by bakefile.
#
# Any manual changes will be lost if it is regenerated,
# modify the source .bkl file instead if possible.

# You may define standard make variables such as CFLAGS or
# CXXFLAGS to affect the build. For example, you could use:
#
#      make CXXFLAGS=-g
#
# to build with debug information. The full list of variables
# that can be used by this makefile is:
# AR, CC, CFLAGS, CPPFLAGS, CXX, CXXFLAGS, LD, LDFLAGS, MAKE, RANLIB.

# You may also specify config=Debug|Release
# or their corresponding lower case variants on make command line to select
# the corresponding default flags values.
ifeq ($(config),debug)
override config := Debug
endif
ifeq ($(config),release)
override config := Release
endif
ifeq ($(config),Debug)
override CPPFLAGS += -DDEBUG
override CFLAGS += -g -O0
override CXXFLAGS += -g -O0
override LDFLAGS += -g
else ifeq ($(config),Release)
override CPPFLAGS += -DNDEBUG
override CFLAGS += -O2
override CXXFLAGS += -O2
else ifneq (,$(config))
$(warning Unknown configuration "$(config)")
endif

# Use "make RANLIB=''" for platforms without ranlib.
RANLIB ?= ranlib

CC := cc
CXX := c++

# The directory for the build files, may be overridden on make command line.
builddir = ./bin

ifneq ($(builddir),.)
_builddir := $(builddir)/
_builddir_error := $(shell mkdir -p $(_builddir) 2>&1)
$(if $(_builddir_error),$(error Failed to create build directory: $(_builddir_error)))
endif
all: lalr

lalr: $(_builddir)lalr_main.o $(_builddir)lalr_automate.o $(_builddir)lalr_etat.o $(_builddir)lalr_lexer.o $(_builddir)lalr_symbole.o
	$(CXX) -o $@ $(LDFLAGS) $(_builddir)lalr_main.o $(_builddir)lalr_automate.o $(_builddir)lalr_etat.o $(_builddir)lalr_lexer.o $(_builddir)lalr_symbole.o -pthread

$(_builddir)lalr_main.o: src/main.cpp
	$(CXX) -c -o $@ $(CPPFLAGS) $(CXXFLAGS) -MD -MP -pthread -Isrc src/main.cpp

$(_builddir)lalr_automate.o: src/automate.cpp
	$(CXX) -c -o $@ $(CPPFLAGS) $(CXXFLAGS) -MD -MP -pthread -Isrc src/automate.cpp

$(_builddir)lalr_etat.o: src/etat.cpp
	$(CXX) -c -o $@ $(CPPFLAGS) $(CXXFLAGS) -MD -MP -pthread -Isrc src/etat.cpp

$(_builddir)lalr_lexer.o: src/lexer.cpp
	$(CXX) -c -o $@ $(CPPFLAGS) $(CXXFLAGS) -MD -MP -pthread -Isrc src/lexer.cpp

$(_builddir)lalr_symbole.o: src/symbole.cpp
	$(CXX) -c -o $@ $(CPPFLAGS) $(CXXFLAGS) -MD -MP -pthread -Isrc src/symbole.cpp

clean:
	rm -f $(_builddir)*.o
	rm -f $(_builddir)*.d
	rm -f $(_builddir)lalr

.PHONY: all clean

# Dependencies tracking:
-include $(_builddir)*.d
